[0.027s] Invoking command in '/home/zhijie/autoware/build/mcity_msg': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/zhijie/autoware/install/simulator_compatibility_test:/home/zhijie/autoware/install/dbw_ford_input_test:/home/zhijie/autoware/install/ad_api_visualizers:/opt/ros/humble /usr/bin/cmake /home/zhijie/autoware/src/terasim/preview_control/mcity_msg -DCMAKE_INSTALL_PREFIX=/home/zhijie/autoware/install/mcity_msg
[0.050s] -- Found ament_cmake_auto: 1.3.5 (/opt/ros/humble/share/ament_cmake_auto/cmake)
[0.316s] -- Found rosidl_generator_c: 3.1.5 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.318s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.322s] -- Found rosidl_generator_cpp: 3.1.5 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.354s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.390s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.736s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.736s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[0.736s]   mcity_msg --arguments-file
[0.736s]   /home/zhijie/autoware/build/mcity_msg/rosidl_adapter__arguments__mcity_msg.json
[0.736s]   --output-dir /home/zhijie/autoware/build/mcity_msg/rosidl_adapter/mcity_msg
[0.736s]   --output-file
[0.736s]   /home/zhijie/autoware/build/mcity_msg/rosidl_adapter/mcity_msg.idls)
[0.736s]   returned error code 1:
[0.736s] 
[0.736s]   Error processing 'float64[] vdVector' of 'mcity_msg/PlanedPath2':
[0.736s]   ''vdVector' is an invalid field name.  It should have the pattern
[0.736s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[0.736s] 
[0.737s]   Traceback (most recent call last):
[0.737s] 
[0.737s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.737s]       return _run_code(code, main_globals, None,
[0.737s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.737s]       exec(code, run_globals)
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.737s]       sys.exit(main())
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.737s]       abs_idl_file = convert_to_idl(
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.737s]       return convert_msg_to_idl(
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.737s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[0.737s]       fields.append(Field(
[0.737s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
[0.737s]       raise NameError(
[0.737s] 
[0.737s]   NameError: 'vdVector' is an invalid field name.  It should have the pattern
[0.737s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[0.738s] 
[0.738s] Call Stack (most recent call first):
[0.738s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.738s]   CMakeLists.txt:77 (rosidl_generate_interfaces)
[0.738s] 
[0.738s] [0m
[0.738s] -- Configuring incomplete, errors occurred!
[0.738s] See also "/home/zhijie/autoware/build/mcity_msg/CMakeFiles/CMakeOutput.log".
[0.740s] Invoked command in '/home/zhijie/autoware/build/mcity_msg' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/zhijie/autoware/install/simulator_compatibility_test:/home/zhijie/autoware/install/dbw_ford_input_test:/home/zhijie/autoware/install/ad_api_visualizers:/opt/ros/humble /usr/bin/cmake /home/zhijie/autoware/src/terasim/preview_control/mcity_msg -DCMAKE_INSTALL_PREFIX=/home/zhijie/autoware/install/mcity_msg
